#Author: Jeremy Xu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petmatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petmatcher
  
  minReadySeconds: 5
  
  template:
    metadata:
      labels:
        app: petmatcher
    spec:
      containers:
      - name: petmatcher
        image: jxu14/petmatcher:latest  # Update with your Docker Hub username and image name
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: petmatcher-service
spec:
  selector:
    app: petmatcher
  type: NodePort  # Use NodePort type
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
